// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv82m6Cc6-6DkyB8g4yg9E8jU86B0mvWw',
    appId: '1:476047317199:web:890aafbbf92c9840417fba',
    messagingSenderId: '476047317199',
    projectId: 'gagans-first-app',
    authDomain: 'gagans-first-app.firebaseapp.com',
    storageBucket: 'gagans-first-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8HcjfosG1eTr4wQzamzLHAkHd_dbmf5Y',
    appId: '1:476047317199:android:ee24d5512e751a3e417fba',
    messagingSenderId: '476047317199',
    projectId: 'gagans-first-app',
    storageBucket: 'gagans-first-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3YoIJ-hZmxD7NyZUuxB9LHT3HOeKSlP0',
    appId: '1:476047317199:ios:9e599c3e084d3178417fba',
    messagingSenderId: '476047317199',
    projectId: 'gagans-first-app',
    storageBucket: 'gagans-first-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3YoIJ-hZmxD7NyZUuxB9LHT3HOeKSlP0',
    appId: '1:476047317199:ios:9e599c3e084d3178417fba',
    messagingSenderId: '476047317199',
    projectId: 'gagans-first-app',
    storageBucket: 'gagans-first-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv82m6Cc6-6DkyB8g4yg9E8jU86B0mvWw',
    appId: '1:476047317199:web:a808290840e42bc3417fba',
    messagingSenderId: '476047317199',
    projectId: 'gagans-first-app',
    authDomain: 'gagans-first-app.firebaseapp.com',
    storageBucket: 'gagans-first-app.firebasestorage.app',
  );
}
